### PR TITLE
Update ServerConfig.java to accomodate modded tools, sand and wood log types

### PR DESCRIPTION
**Pull request by tpl20000**
Added general forge tags so modded tools would be affected too. Also added forge sand tag, since some mods may add trees on sand , and forge logs to account for modded wood log types.

### CODE REVIEW

**Comment by henkelmax** [comment]
Did you test if this works?

**Comment by tpl20000** [comment]
> Did you test if this works?

Yes, this works. However, there are some issues.
It appears some mods (Biomes O'Plenty, for example) add trees that grow on sand, which does not have general tags (i.e. minecraft:sand does not exist). One solution would be to manually write down tags for each sand block individually. Once done, we will apply some changes here...

**Comment by tpl20000** [comment]
We are currently investigating, but yes, it works.
We found some more general tags (and a mistake) that we would like to add (fix)

**Comment by henkelmax** [comment]
> We are currently investigating, but yes, it works.

That's weird, because this is not supposed to work. Tag entries should start with a `#` in order to work.
image

**Comment by tpl20000** [comment]
> > We are currently investigating, but yes, it works.
> 
> That's weird, because this is not supposed to work. Tag entries should start with a `#` in order to work. image

We just finished investigating and fixed these issues and commited changes. :D

**Comment by henkelmax** [comment]
Adding support for general `#minecraft:crops` is not recommended, as some modded crops are not supposed to be harvested. Even some vanilla crops aren't harvestable.

`#minecraft:crops` also doesn't include nether warts.

`#minecraft:logs` also includes stripped logs and barks, which is not wanted. This will cause players builds potentially being harvested.

`#forge:axes` and `#forge:tools/paxels`  does not exist in NeoForge.

You clearly haven't tested your additions but told me that they work.

> We are currently investigating, but yes, it works.

**Pull request closed without merging**
